a=input("ENTER YOUR NAME : ")
b=int(input("ENTER YOU SID : "))
c=input("ENTER YOUR DEPARTMENT : ")
d=float(input("ENTER YOUR CGPA : "))
print("Hey,",a," Here!")
print("My SID is ",b,".")
print("I am from ",c," department and my CGPA is ",d,".")